#!/bin/bash
#
# %1$s
#
# chkconfig: - 85 15
# description: start, stop, restart %1$s
#

RETVAL=0

case "$1" in
    start)
      %2$s
      RETVAL=$?
  ;;
    stop)
      kill `cat /var/run/%1$s.pid`
      RETVAL=$?
  ;;
    restart)
      kill `cat /var/run/%1$s.pid`
      %2$s
      RETVAL=$?
  ;;
    status)
      RETVAL=$?
  ;;
    *)
      echo "Usage: %1$s {start|stop|restart}"
      exit 1
  ;;
esac

exit $RETVAL